######################
#      ANSIBLE       #
######################
pip_package: python3-pip
pip_executable: pip3
pip_install_packages:
  - name: setuptools
    state: latest
ansible_install_method: pip