---
- hosts: grafana
  become: true
  tasks:
    - name: Import Grafana public key 
      apt_key: url=https://packages.grafana.com/gpg.key state=present

    - name: Add Grafana repo 
      apt_repository: 
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
      tags:
      - grafana
      - grafana::install

- hosts: grafana
  become: true
  roles:
    - manala.grafana
  tags:
    - grafana
    - grafana::setup
