---

# UPDATE & IMPORT INFLUXDB KEY
- hosts: all
  become: true
  tasks: 
    - name: Set timezone to Europe/Paris
      timezone:
        name: Europe/Paris
        
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
        
    - name: Import InfluxDB GPG public key 
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present

    - name: Add InfluxDB repo 
      apt_repository: 
        repo: "deb https://repos.influxdata.com/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower}} stable"
        state: present
        filename: influxdb

# ANSIBLE INSTALL
# doc: https://github.com/geerlingguy/ansible-role-ansible

- hosts: ansible
  become: true
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - geerlingguy.pip
    - geerlingguy.ansible
  tags:
    - ansible
    - ansible::install

- hosts: influxdb
  become: true
  roles: 
    - manala.influxdb
    - influxDB-retention-policy
  tags:
    - influxdb
    - influxdb::install
    - influxdb::config

# INSTALL TELEGRAF
    
- import_playbook: telegraf.yml

# INSTALL GRAFANA
# doc: https://github.com/manala/ansible-role-grafana

- hosts: grafana
  become: true
  tasks:
    - name: Import Grafana public key 
      apt_key: url=https://packages.grafana.com/gpg.key state=present

    - name: Add Grafana repo 
      apt_repository: 
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
      tags:
      - grafana
      - grafana::install

- hosts: grafana
  become: true
  roles:
    - manala.grafana
  tasks:
    - name: Install plugins
      command: grafana-cli plugins install "{{ item }}"
      with_items: "{{ grafana_plugins }}"
    
    - name: grafana restart
      service:
        name: grafana-server
        state: restarted

  tags:
    - grafana
    - grafana::setup
