project_tag: local_monitoring

############
# INFLUXDB #
############
influxdb_monitoring_db: "monitoring"
influxdb_telegraf_user: "telegraf_probe"
influxdb_telegraf_pass: "very_secret"

influxdb_grafana_user: "grafana"
influxdb_grafana_pass: "very_secret"
influxdb_ip: "{{ groups['influxdb'] | map('extract', hostvars, ['ansible_ssh_host']) | join(':8086\",\"http://') }}"

############
# TELEGRAF #
############

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://{{ influxdb_ip }}:8086"]
      - database = "{{ influxdb_monitoring_db }}"
      - username = "{{ influxdb_telegraf_user }}"
      - password = "{{ influxdb_telegraf_pass }}"

############
# GRAFANA  #
############

grafana_ip: "{{ groups['grafana'] | map('extract', hostvars, ['ansible_ssh_host'])  | first }}"
grafana_admin: admin
grafana_admin_pass: adminpass

grafana_expose_port: 3000

manala_grafana_config:
  - app_mode: production
  - server:
      - http_port: "{{ grafana_expose_port }}"
  - security:
      - admin_user: "{{ grafana_admin }}"
      - admin_password: "{{ grafana_admin_pass }}"

manala_grafana_api_url: "http://127.0.0.1:{{ grafana_expose_port }}"
manala_grafana_api_user: "{{ grafana_admin }}"
manala_grafana_api_password: "{{ grafana_admin_pass }}"

manala_grafana_datasources:
  - name:      telegraf
    type:      influxdb
    isDefault: true
    access:    server
    basicAuth: false
    url:       "http://{{ influxdb_ip }}:8086"
    database:  "{{ influxdb_monitoring_db }}"
    username:  "{{ influxdb_grafana_user }}"
    password:  "{{ influxdb_grafana_pass }}"
