roles:
    - name: geerlingguy.pip
      version: 2.0.0

    - name: geerlingguy.ansible
      version: 2.1.0

    - name: manala.influxdb
      version: 2.0.2
      
    - name: dj-wasabi.telegraf
      version: 0.13.0
 
    - name: manala.grafana
      version: 2.0.2

# - src: https://XXXXX/springboot.git
#   scm: git
#   name: external_roles/springboot_tools
#   version: '1.9.0'
