roles:
    - name: geerlingguy.pip
      version: 2.0.0

    - name: geerlingguy.ansible
      version: 2.1.0

    - name: manala.influxdb
      version: 2.0.2
    #- name: manala.telegraf
    #  version: 2.0.10
    - name: dj-wasabi.telegraf
      version: 0.13.0