# Politique de retention de données
- name: Création Retention Policy 
  uri:
    url: "{{ URLQuery }}"
    method: POST
    body_format: "form-urlencoded"
    body: "{{ item.query }}"
  with_items: "{{ retention_policies }}"
  register: response

- name: Création Continuous Query 
  uri:
    url: "{{ URLQuery }}"
    method: POST
    body_format: "form-urlencoded"
    body: "{{ item.query }}"
  with_items: "{{ continuous_queries }}"
  register: response2
  
# - name: "Debug"
#   debug:
#     var: response2