project_tag: devops-monitoring

influx_ip: "{{ groups['influxdb'] | map('extract', hostvars, ['ansible_ssh_host']) | join(':8086\",\"http://') }}"
######################
#      ANSIBLE       #
######################
pip_package: python3-pip
pip_executable: pip3
pip_install_packages:
  - name: setuptools
    state: latest
ansible_install_method: pip

############
# InfluxDB #
############
# doc : https://github.com/manala/ansible-role-influxdb
manala_influxdb_databases:
  - "{{ influxdb_monitoring_db }}"

manala_influxdb_users:
  - database: "{{ influxdb_monitoring_db }}"
    name: "{{ influxdb_telegraf_user }}"
    password: "{{ influxdb_telegraf_pass }}"

  - database: "{{ influxdb_monitoring_db }}"
    name: "{{ influxdb_grafana_user }}"
    password: "{{ influxdb_grafana_pass }}"

manala_influxdb_privileges:
  - database: "{{ influxdb_monitoring_db }}"
    user: "{{ influxdb_telegraf_user }}"
    grant: write

  - database: "{{ influxdb_monitoring_db }}"
    user: "{{ influxdb_grafana_user }}"
    grant: read

manala_influxdb_dir:
  - /var/lib/influxdb/meta
  - /var/lib/influxdb/data
  - /var/lib/influxdb/wal

manala_influxdb_config:
  - reporting-disabled: true
  - meta:
    - dir: /var/lib/influxdb/meta
  - data:
    - dir: /var/lib/influxdb/data
    - wal-dir: /var/lib/influxdb/wal
  - udp:
    - enabled: false

#############
#  Grafana  #
#############

manala_grafana_config:
  - app_mode: production
  - server:
      - http_port: 3000
  - security:
      - admin_user: admin
      - admin_password: admin

manala_grafana_api_url: http://127.0.0.1:3000
manala_grafana_api_user: admin
manala_grafana_api_password: admin

manala_grafana_datasources:
  - name:      telegraf
    type:      influxdb
    isDefault: true
    access:    server
    basicAuth: true
    url:       "http://{{ influx_ip }}:8086"
    database:  "{{ influxdb_monitoring_db }}"
    username:  "{{ influxdb_grafana_user }}"
    password:  "{{ influxdb_grafana_pass }}"
