---
############
# MAIN VAR #
############
project_tag: default

influxdb_monitoring_db: "monitoring"
influxdb_telegraf_user: "telegraf_probe"
influxdb_telegraf_pass: "very_secret"


############
# TELEGRAF #
############
# doc: https://github.com/manala/ansible-role-telegraf

telegraf_agent_package_method: repo
telegraf_agent_package_state: latest
telegraf_agent_debug: "false"
telegraf_agent_hostname: "{{ ansible_nodename }}"
telegraf_agent_quiet: "true"
#telegraf_win_install_dir: "C:\Telegraf"
#telegraf_win_logfile: "C:\Telegraf\log"
#telegraf_win_include: "C:\Telegraf\plugins"
telegraf_agent_logfile: /var/log/telegraf/telegraf.log
telegraf_agent_interval: "10"
telegraf_agent_flush_interval: "10"

telegraf_global_tags:
  - tag_name: projet
    tag_value: "{{ project_tag }}"

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://{{ groups['influxdb'] | map('extract', hostvars, ['ansible_ssh_host']) | join(':8086\",\"http://') }}:8086"]
      - database = "{{ influxdb_monitoring_db }}"
      - username = "{{ influxdb_telegraf_user }}"
      - password = "{{ influxdb_telegraf_pass }}"

telegraf_plugins_default:
  - plugin: system
  - plugin: cpu
  - plugin: mem
  - plugin: disk
  - plugin: netstat