{
 "title": "System",
 "description": "By Ghislain LE MEUR",
 "tags": [
  "telegraf",
  "influxdb",
  "host",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now-30s" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\" WHERE PROJECT == TEAM1"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\""
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES FROM \"network\" WITH KEY = \"device\""
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "select last(uptime_format) from system where  host =~ /^$host$/",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "cpus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT mean(\"n_cpus\") FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "user",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "total processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "processes",
     "query": "SELECT last(\"total\") FROM \"processes\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "total threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "processes",
     "query": "SELECT last(\"total_threads\") FROM \"processes\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "load 1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load1\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "load 5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "load 15",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load15\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "query": "SELECT last(used_percent) FROM \"mem\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk used (max)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "disk",
     "query": "SELECT max(used_percent) FROM \"disk\" WHERE \"host\" =~ /^$host$/ and \"device\" != 'rootfs'  and $timeFilter",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "query": "SELECT mean(\"pct_steal\") AS \"steal\", mean(\"pct_nice\") AS \"nice\", mean(\"pct_iowait\") AS \"iowait\", mean(\"pct_system\") AS \"system\", mean(\"pct_user\") AS \"user\", 100 - mean(\"pct_idle\") AS \"total\" FROM \"cpu_util\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pct_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ],
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU used per CPUs ($cpu)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "select blocked,running,sleeping,total,total_threads,zombies from processes where  host =~ /^$host$/ and $timeFilter",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "zombies" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Memory / Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cache" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% swap" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IO swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path ($tag_fstype on $tag_device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /^$host$/ and $timeFilter GROUP BY time($interval), \"path\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk inode used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path ($tag_fstype on $tag_device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"inodes_used\") / inodes_total FROM \"disk\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ mean(inodes_total)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk busy ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "pct_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "util" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk throughput ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"rkB_per_s\") AS \"read\", mean(\"wkB_per_s\") AS \"write\" FROM \"disk\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO/s ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk await ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "await" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk queue size ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "avgqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO size ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "avgrq-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512" ], "type": "math" },
       { "params": [ "request size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Network throughput ($interface)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$tag_device $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "rxkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "txkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$interface$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network errors ($interface)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "rxerr_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "txerr_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(tcp_established)   FROM \"netstat\" WHERE $timeFilter and \"host\" =~ /^$host$/ GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_close" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_close_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_close_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_closing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_colsing" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_fin_wait1" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_fin_wait2" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_last_ack" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_last_ack" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_syn_recv" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_syn_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_listen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_listen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_time_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_time_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "udp_socket" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "udp_socket" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_established" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}