URLQuery: "http://localhost:8086/query?db=myBigDatabase&"

# Retention Policy Requests

retention_policies: 
  - name: "RP1"
    query: "q=CREATE RETENTION POLICY RP1 ON myBigDatabase DURATION 1w REPLICATION 1 DEFAULT"
  - name: "RP2"
    query: "q=CREATE RETENTION POLICY RP2 ON myBigDatabase DURATION 2w REPLICATION 1"
  - name: "RP3"
    query: "q=CREATE RETENTION POLICY RP3 ON myBigDatabase DURATION 3w REPLICATION 1"

# Continuous Queries Requests

continuous_queries: 
  - name: "CQ1"
    query: "q=CREATE CONTINUOUS QUERY CQ1 on myBigDatabase RESAMPLE EVERY 1h FOR 1h BEGIN SELECT mean(*) INTO RP2.:MEASUREMENT FROM /.*/ GROUP BY time(1m), * END"
  - name: "CQ2"
    query: "q=CREATE CONTINUOUS QUERY CQ2 on myBigDatabase RESAMPLE EVERY 2h FOR 2h BEGIN SELECT mean(*) INTO RP3.:MEASUREMENT FROM RP2./.*/ GROUP BY time(10m), * END"
