URLQuery: "http://localhost:8086/query?db=monitoring&"

# Retention Policy Requests

retention_policies: 
  - name: "RP1month"
    query: "q=CREATE RETENTION POLICY RP1month ON monitoring DURATION 4w REPLICATION 1 DEFAULT"
  - name: "RP3month"
    query: "q=CREATE RETENTION POLICY RP3month ON monitoring DURATION 12w REPLICATION 1"
  - name: "RP6month"
    query: "q=CREATE RETENTION POLICY RP6month ON monitoring DURATION 24w REPLICATION 1"

# Continuous Queries Requests

continuous_queries: 
  - name: "RP1toRP3"
    query: "q=CREATE CONTINUOUS QUERY RP1toRP2 on monitoring RESAMPLE EVERY 1h FOR 1h BEGIN SELECT mean(*) INTO RP3month.:MEASUREMENT FROM /.*/ GROUP BY time(1m), * END"
  - name: "RP3toRP6"
    query: "q=CREATE CONTINUOUS QUERY RP2toRP3 on monitoring RESAMPLE EVERY 2h FOR 2h BEGIN SELECT mean(*) INTO RP6month.:MEASUREMENT FROM RP3month./.*/ GROUP BY time(10m), * END"
